sudo: required
language: generic

services: 
  - docker


before_install:
  - docker build -t hsedecanter/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true hsedecanter/docker-react npm run test